### PR TITLE
Remove vendored three.js and ros3djs.

### PR DESCRIPTION
**Pull request by SirVer**
This also includes the 3 lines from my other pull request which should be merged first. If you do not want the other PR, I will remove the lines here too.

### CODE REVIEW

**Comment by jstnhuang** [comment]
Hi, I get this error when running `bower update`:

```
bower ros3djs#^0.17.0                    ENORESTARGET No tag found that was able to satisfy ^0.17.0

Additional error details:
Available versions in git://github.com/RobotWebTools/ros3djs.git: 0.15.0, 0.14.0, 0.13.0, 0.12.0, 0.11.0, 0.9.0, 0.8.0
```

So I think we would need to use 0.15.0.

However, vendoring is probably better for now. I had to copy some unreleased changes from ros3djs:  925e7606914548157213112530d13a768f094d1b and ff63583a5be3807263fe6128625230f9f0bf7701, but I don't remember the exact rationale. I think one of them was to change the tf prefix for the URDF (to dynamically switch robot displays) and the other was to make the point cloud display faster.

**Comment by SirVer** [comment]
Vendoring is always a bad idea - you effectively forked the downstream repository which makes it harder for your clients (me) to use both the downstream library and yours. 

Once ros3djs adds the bower configuration (linked above) the error should go away - we have to wait on that for sure. Once they merged, you also should have then all the changes you hoisted into your version, since we directly depend on the current git version of ros3djs.

**Comment by SirVer** [comment]
Could you try again, now that the ros3djs one is merged?

**Comment by jstnhuang** [comment]
Same error, are you able to do it yourself?

**Comment by SirVer** [comment]
it does work for me :/.

**Pull request closed without merging**
