### PR TITLE
Add TF displays

### PR DESCRIPTION
**Pull request by chapulina**
This addresses #21. See https://github.com/osrf/polymer-ros-rviz/pull/8 for more context.

@jstnhuang , let us know what you think! We would love it if you could merge this and #6  and publish a new version of `ros-rviz`! As a reference, we've been using your components on https://github.com/osrf/rvizweb :smiley: 

Here's a quick demo:

tfgif

### CODE REVIEW

**Comment by chapulina** [comment]
Thank you for merging the two PRs, @jstnhuang! Do you have any plans of making a new release soon? Is there anything we can help with?

Thanks again!

**Comment by jstnhuang** [comment]
Hi @chapulina, I just tagged a release on Github. I hope to make a release on webcomponents.org. However, a new requirement for publishing on webcomponents.org is to first publish the package on NPM. This will require some work to migrate and might take a few weeks. I already started by migrating the `<ros-websocket>` element to NPM.

**Comment by jubeira** [comment]
Thanks @jstnhuang; please let us know if we can help you with the migration. Perhaps with some pointers we can make it easier for you and speed it up a bit.

**Comment by chapulina** [comment]
@jstnhuang , we just noticed the 3.1.1 version on webcomponents,org, thanks a bunch for handling this so quickly!

**Comment by jstnhuang** [comment]
Thanks for the offer! Just to be clear, a component doesn't really need to be published on webcomponents.org at all. A project's bower.json file specifies the version as described here: https://bower.io/docs/api/#install. So you can specify a specific Github release like 3.1.1, or version ranges like 3.1 or 3. Or, you can even specify a specific commit (in fact, I've pinned this project's ros3djs to a specific commit). webcomponents.org is mostly helpful for people to browse components and view documentation.

The migration work is related to the new Polymer 3 release, which uses NPM instead of bower for dependency management. I'm not sure if migrating to NPM is a backwards compatible change, so it might not even be a great idea.

**Comment by chapulina** [comment]
Thank you for the info, @jstnhuang! Using specific Github tags in the future will sure speed things up.

**Pull request merged**
